### ISSUE TITLE
thewilly name is set to paulino álvarez ondina

### ISSUE THREAD

**Issue by thewilly** [weso/weso.github.io#1]
At the moment the name that appears in the webpage for Guillermo Facundo Colunga is Paulino Álvarez Ondina. You can see in the following lines the div corresponding to thewilly.
https://github.com/weso/weso.github.io/blob/e040fbb4af8965393771cd456133e1b532354a81/index.html#L2400-L2411

**Comment by labra** [comment]
:smile: Changed!!
